'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),E=require('../assets/engine.js');
const meta={kind:'crypto',timeframe:'1d',annualDays:365,multiplier:1,tick:0};
function bars(cs){return cs.map((c,i)=>({t:Date.UTC(2024,0,1+i)/1000,day:new Date(Date.UTC(2024,0,1+i)).toISOString().slice(0,10),o:c,h:c+1,l:c-1,c,v:100,contract:'',factor:1,rawO:c,rawH:c+1,rawL:c-1,rawC:c,rollOldOpen:null,gap:false}));}
const cfg={n:3,fast:2,slow:4,atrN:3,initial:10000,feeBps:3,slipBps:2};
test('SF01 transforms OHLC and shifts its boundary by one completed bar',()=>{const b=bars([10,12,11,99]);b[0].o=9;b[1].o=13;b[2].o=10;const x=E.indicators(b,{...E.DEFAULTS,...cfg,strategy:'sf01'});A.equal(x.upper[2],null);A.equal(x.upper[3],14);A.equal(x.lower[3],8);});
test('SF01 current extreme cannot expand the entry threshold',()=>{const b=bars([10,11,12,99]);const p={...E.DEFAULTS,...cfg,strategy:'sf01'};const a=E.indicators(b,p);b[3].h=9999;const c=E.indicators(b,p);A.equal(a.upper[3],c.upper[3]);});
test('both SuperTrend variants have full warmup and finite lines',()=>{for(const variant of ['hl2','kama']){const b=bars([10,11,12,13,14,15,11,10,9]);const x=E.supertrend(b,3,1,variant);A.deepEqual(x.line.slice(0,2),[null,null]);A.ok(x.line.slice(3).every(Number.isFinite));A.ok(x.direction.includes(-1));}});
test('new indicators and exits preserve prefixes including fills',()=>{const b=bars(Array.from({length:160},(_,i)=>100+.2*i+10*Math.sin(i/4)));for(const strategy of ['sf01','supertrend','boll_break'])for(const exitType of Object.keys(E.EXIT_TYPES))for(const stVariant of ['hl2','kama']){const p={...cfg,strategy,exitType,stVariant,forceClose:false,exitMode:'replace',allowShort:true};const x=E.run(b.slice(0,90),meta,p),y=E.run(b,meta,p);A.deepEqual(x.fills,y.fills.filter(f=>f.index<90));A.deepEqual(x.signals,y.signals.filter(f=>f.signalIndex<89));A.deepEqual(x.stopLine,y.stopLine.slice(0,90));}});
test('percentage protection fills at a worse gap open, not the ideal line',()=>{const b=bars([100,101,102,80,79]);const x=E.run(b,meta,{...cfg,strategy:'buyhold',exitType:'percent',trailPct:5,exitMode:'replace'});const f=x.fills.find(f=>f.kind==='stop');A.equal(f.index,3);A.equal(f.raw,80);});
test('chandelier uses the high only for the next bar and differs from close-ATR',()=>{const b=bars([100,101,102,103,104,105,106]);b[3].h=130;b[3].rawH=130;const p={...cfg,strategy:'buyhold',exitMode:'replace',atrK:2};const a=E.run(b,meta,{...p,exitType:'atr'}),c=E.run(b,meta,{...p,exitType:'chandelier'});A.ok(!c.fills.some(f=>f.kind==='stop'&&f.index===3));A.ok(c.fills.some(f=>f.kind==='stop'&&f.index===4));A.ok(!a.fills.some(f=>f.kind==='stop'&&f.index===4));});
test('percentage and inverse-volatility stop ratchets cannot loosen while held',()=>{const b=bars(Array.from({length:100},(_,i)=>100+i));for(const exitType of ['atr','chandelier','percent','invvol']){const x=E.run(b,meta,{...cfg,strategy:'buyhold',exitType,exitMode:'replace',trailPct:20});for(const t of x.trades){const a=x.stopLine.slice(t.entryIndex,t.exitIndex).filter(v=>v!=null);for(let i=1;i<a.length;i++)A.ok(a[i]>=a[i-1]-1e-9);}}});
test('inverse volatility means tighter percentage when ATR% doubles, with caps',()=>{const p={...E.DEFAULTS,exitType:'invvol'};A.equal(E.trailingDistance(p,.02,.02),.05);A.equal(E.trailingDistance(p,.04,.02),.025);A.equal(E.trailingDistance(p,0,.02),.2);A.equal(E.trailingDistance(p,5,.02),.01);});
test('replace ignores native reversals, overlay does not',()=>{const b=bars([100,101,102,103,102,101,100,99,98]);const p={...cfg,exitType:'percent',trailPct:50};const x=E.run(b,meta,{...p,exitMode:'overlay'}),y=E.run(b,meta,{...p,exitMode:'replace'});A.equal(y.trades[0].forced,true);A.equal(x.trades[0].forced,false);});
test('fresh re-entry suppresses repeated entries while a stopped condition persists',()=>{const b=bars([100,101,102,103,104,105,106]);b[3].l=90;b[3].rawL=90;const p={...cfg,strategy:'buyhold',exitType:'percent',trailPct:5};const a=E.run(b,meta,{...p,reentry:'fresh'}),c=E.run(b,meta,{...p,reentry:'state'});A.equal(a.trades.length,1);A.ok(c.trades.length>a.trades.length);});
test('new exits reconcile full-history trade costs and equity',()=>{const b=bars(Array.from({length:300},(_,i)=>100+i/10+14*Math.sin(i/5)));for(const exitType of Object.keys(E.EXIT_TYPES))for(const strategy of ['sf01','supertrend']){const r=E.run(b,meta,{...cfg,strategy,exitType,allowShort:true});A.ok(Math.abs(r.stats.net-r.trades.reduce((s,t)=>s+t.net,0))<1e-7);}});
test('invalid exit type and bounds fail clearly',()=>{A.throws(()=>E.validateSettings({exitType:'wrong'}));A.throws(()=>E.validateSettings({invMin:20,invMax:1}));A.throws(()=>E.validateSettings({trailPct:100}));});
