'use strict';
const {test}=require('node:test'),A=require('node:assert/strict');
const E=require('../assets/engine.js'),S=require('../assets/study.js');
const meta={kind:'crypto',timeframe:'1d',annualDays:365};
function bars(n=120){return Array.from({length:n},(_,i)=>{const c=100+10*Math.sin(i/7)+i*.1;return {t:Date.UTC(2024,0,i+1)/1000,day:new Date(Date.UTC(2024,0,i+1)).toISOString().slice(0,10),o:c,h:c+2,l:c-2,c,rawO:c,rawH:c+2,rawL:c-2,rawC:c,factor:1,v:100,contract:'',gap:false};});}
test('all eight strategies have distinct daily/hourly valid fixed presets',()=>{A.equal(S.ORDER.length,8);for(const strategy of S.ORDER){for(const tf of ['1d','1h']){const p=E.validateSettings({...S.preset(strategy,tf),strategy});A.equal(p.exitType,'native');A.equal(p.stop,false);A.ok(p.fast<p.slow);}A.notEqual(S.preset(strategy,'1h').n,S.preset(strategy,'1d').n);}});
test('presets return fresh objects, preserving reproducibility after edits',()=>{const p=S.preset('sma','1d');p.n=999;A.equal(S.preset('sma','1d').n,20);A.throws(()=>S.preset('unknown','1d'));});
test('lessons define six system stages and a valid acyclic comparison graph',()=>{A.equal(S.FLOW.length,6);for(const strategy of S.ORDER){const seen=new Set();let k=strategy;while(k){A.ok(!seen.has(k));seen.add(k);A.ok(S.LESSONS[k]);k=S.LESSONS[k].parent;}const p=E.validateSettings({...S.preset(strategy,'1d'),strategy});A.equal(S.flowCards(strategy,p,E).length,6);}});
test('display explains replace versus overlay and fresh versus state re-entry',()=>{const p=E.validateSettings({strategy:'boll_break',exitType:'chandelier',exitMode:'replace',reentry:'fresh'});A.match(S.flowCards('boll_break',p,E)[3],/忽略原正常退出/);A.match(S.flowCards('boll_break',p,E)[4],/先失效/);});
test('entry explanation reports actual signal indicator, not future exit indicator',()=>{const b=bars(),r=E.run(b,meta,{strategy:'sma',n:5});const t=r.trades.find(t=>!t.forced),d=S.explainTrade(b,r,t);const v=r.indicators.single[t.entrySignalIndex].toLocaleString('en-US',{maximumFractionDigits:4});A.ok(d.entry.includes(v));A.match(d.entry,/信号价格坐标/);A.match(d.execution,/含滑点/);});
test('terminal valuation is not described as a normal strategy exit',()=>{const b=bars(),r=E.run(b,meta,{strategy:'sma',n:5,allowShort:true}),t=r.trades.find(t=>t.forced);A.ok(t);A.match(S.explainTrade(b,r,t).exit,/不是趋势或通道/);});
test('protective exits report the pre-existing stop and keep accounting unchanged',()=>{const b=bars(),r=E.run(b,meta,{strategy:'boll_break',n:5,k:1,exitType:'percent',trailPct:2}),t=r.trades.find(t=>t.stopExit);A.ok(t);const before=JSON.stringify(r.stats);A.match(S.explainTrade(b,r,t).exit,/事先确定的保护线/);A.equal(JSON.stringify(r.stats),before);});
test('only continuous futures with differing factors have switchable price scales',()=>{A.equal(S.priceCapability([{factor:1}],{kind:'crypto'}).canSwitch,false);A.equal(S.priceCapability([{factor:1}],{kind:'future'}).canSwitch,false);A.equal(S.priceCapability([{factor:1},{factor:1.2}],{kind:'future'}).canSwitch,true);});

test('published HTML loads all versioned assets in dependency order',()=>{const fs=require('node:fs'),path=require('node:path'),root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');const scripts=[...html.matchAll(/<script defer src="([^"?]+)(?:\?[^" ]*)?"><\/script>/g)].map(x=>x[1]);A.deepEqual(scripts,['data/catalog.js','assets/engine.js','assets/charts.js','assets/study.js','assets/workspace.js','assets/app.js']);for(const file of scripts.filter(x=>x.startsWith('assets/')))A.ok(fs.existsSync(path.join(root,file)));A.equal((html.match(/<canvas /g)||[]).length,1);A.match(html, /assets\/workspace\.css\?v=1\.2\.0/);});
