'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const ROOT=path.resolve(__dirname,'..'),E=require('../assets/engine.js'),ctx={window:{}};
vm.runInNewContext(fs.readFileSync(path.join(ROOT,'data/catalog.js'),'utf8'),ctx);
const cat=ctx.window.CTA_CATALOG,checks=[];let runs=0;
for(const d of cat.datasets){const content=fs.readFileSync(path.join(ROOT,d.file));assert.equal(crypto.createHash('sha256').update(content).digest('hex'),d.sha256,d.id+' hash');vm.runInNewContext(content.toString(),ctx);const pack=ctx.window.CTADATA[d.id],bars=E.unpack(pack);assert.equal(bars.length,d.rows);for(let i=0;i<bars.length;i++){const b=bars[i];assert.ok(b.o>0&&b.c>0&&b.h>=Math.max(b.o,b.c)-1e-7&&b.l<=Math.min(b.o,b.c)+1e-7,d.id+' OHLC');if(i)assert.ok(b.t>bars[i-1].t,d.id+' sorted');if(b.contract&&bars[i-1]?.contract!==b.contract&&i)assert.ok(b.rollOldOpen>0,d.id+' roll leg');if(d.kind==='crypto'&&d.timeframe==='1d')assert.equal(b.t%86400,0);}
for(const strategy of Object.keys(E.STRATEGIES)){const r=E.run(bars,pack.meta,{...E.DEFAULTS,strategy,allowShort:d.kind==='future'});const net=r.trades.reduce((s,t)=>s+t.net,0);assert.ok(Math.abs(net-r.stats.net)<1e-5*Math.max(1,Math.abs(net)),d.id+' reconcile '+strategy);assert.ok(r.fills.every(f=>f.signalIndex==null||f.signalIndex<f.index),d.id+' causal execution');assert.ok(Number.isFinite(r.stats.final));runs++;}
for(const strategy of ['sf01','boll_break'])for(const exitType of ['atr','chandelier','percent','invvol']){const r=E.run(bars,pack.meta,{...E.DEFAULTS,strategy,exitType,exitMode:'replace',allowShort:d.kind==='future'});assert.ok(Math.abs(r.trades.reduce((v,t)=>v+t.net,0)-r.stats.net)<1e-4*Math.max(1,Math.abs(r.stats.net)),d.id+' exit reconciliation '+exitType);assert.ok(Number.isFinite(r.stats.final));runs++;}
const st=E.run(bars,pack.meta,{...E.DEFAULTS,strategy:'supertrend',stVariant:'kama',allowShort:d.kind==='future'});assert.ok(Number.isFinite(st.stats.final));runs++;
checks.push({id:d.id,rows:d.rows,configurations:18,passed:true});delete ctx.window.CTADATA[d.id];}
const out={engineVersion:E.VERSION,datasets:checks.length,backtestRuns:runs,checks,notes:['所有89个数据包核对SHA256、OHLC和时间排序。','9种规则包括持续做多基准；另测8种退出组合与KAMA趋势变体。','这些是实现验证，不是策略盈利能力或实盘可成交性证明。']};fs.writeFileSync(path.join(ROOT,'docs/data-audit-results.json'),JSON.stringify(out,null,2));console.log(`PASS: ${checks.length} datasets, ${runs} full-history backtests`);
